### ISSUE TITLE
Xcode 12.3 final audit checklist

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10165]
# Things to review before release

- [x] NetworkExtension `NEAppProxyFlow` `isBound` not responding on iOS 14.3 beta 1 (but it's only shown in macOS, not iOS, headers so far)
   - added in Xcode 12.3 RC, bindings updated for iOS in https://github.com/xamarin/xamarin-macios/pull/10240

# From Xcode 12.2 checklist

- [x] [Enable watchOS tests again](https://github.com/xamarin/xamarin-macios/blob/6e8eed3e76c7a222ca5009ac8133985013963fa1/tests/xharness/Jenkins/Jenkins.cs#L38)
   - backport for d16-8 https://github.com/xamarin/xamarin-macios/pull/10133 needs to be merged first
   - mostly fixed with https://github.com/xamarin/xamarin-macios/pull/10196
   - SIGFPE issue -> https://github.com/mono/mono/issues/20632
- [x] Check on `MediaAccessibility/ImageCaptioningTest.cs` `SetCaption` tests, added a parrot for Beta 2
   - seems fixed, PR https://github.com/xamarin/xamarin-macios/pull/10172 to confirm
- [x] Double check ModelIO and remove ignore added here https://github.com/xamarin/xamarin-macios/pull/9844
   - still crashing with Xcode 12.3 beta 1 (tested on DTK)
   - fixed in macOS 11.1 beta 2, re-enabled with https://github.com/xamarin/xamarin-macios/pull/10239
- [ ] Check on `CoreSpotlight.CSLocalizedString` not a hard blocker since it is also broken in GM
   - still crashing with Xcode 12.3 beta 1, still crashing with macOS 11.1 beta 2
