### ISSUE TITLE
.NET 6: add arm64 support to Mac Catalyst and macOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10700]
* [x] Fix generator to produce correct binding code for ARM64
    * [x] Fixed in #10115.
* [x] Add ARM64 support to Mac Catalyst. We already have runtime packs.
* [x] Add ARM64 support to macOS
    * [x] Blocked on ARM64-runtime packs for macOS (https://github.com/dotnet/runtime/issues/48531).
    * [x] Fixed in #10959.
* [x] Add testing support in xharness.
* [x] The runtime packs for macOS and Mac Catalyst don't work on ARM64 (https://github.com/dotnet/runtime/issues/52635)
* [x] AOT-compile on ARM64 for Mac Catalyst (https://github.com/xamarin/xamarin-macios/issues/11724).

**Comment by rolfbjarne** [comment]
This is all done now.
