### ISSUE TITLE
[dotnet][catalyst] Missing or not working tests configurations

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10833]
not exhaustive lists...

# Missing
...from xharness

* don't link
  * [x] Mac [dotnet]
  * [x] tvOS [dotnet]
  * [x] Mac Catalyst [dotnet] -> #12154
* introspection
  * [x] Mac [dotnet]
  * [x] Mac Catalyst [dotnet] -> #12039
      * Tracked in #10215.
      * Fixed in ##12329.
* interdependent-binding-projects 
  * [x] Mac [dotnet]
  * [x] Mac Catalyst [dotnet]
  * [x] tvOS [dotnet]
* link all
  * [x] Mac [dotnet]
  * [x] Mac Catalyst [dotnet] #12154
  * [x] tvOS [dotnet]
* link sdk
  * [x] Mac [dotnet]
  * [x] Mac Catalyst [dotnet] #12154
  * [x] tvOS [dotnet]
* monotouch-test
  * [x] tvOS [dotnet]

# Not working
...but available to run from xharness

* introspection
  * [x] ~Mac Catalyst -> build failure~This is not needed anymore.

**Comment by rolfbjarne** [comment]
This is all done now.
