### ISSUE TITLE
Xcode 13: list of changes to be reviewed/reverted before final release

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11883]
* [x] ~[[SimInstaller] Xcode13.0 cannot install simulators](https://github.com/xamarin/xamarin-macios/issues/11881)~
* [ ] [WKPreferences isTextInteractionEnabled is not correctly bound on xcode13.](https://github.com/xamarin/xamarin-macios/issues/11955)
* [ ] [[AuthenticationServices] StronglyTypedNSArray Recommendation](https://github.com/xamarin/xamarin-macios/issues/12044)
* [x] [[AuthenticationServices] SecKey Not Usable inside AuthenticationServices Binding](https://github.com/xamarin/maccore/issues/2482)
* [ ] [[QuickLook] QLPreviewSceneActivationConfiguration not yet bound in Xcode13](https://github.com/xamarin/xamarin-macios/issues/12335)
* [ ] [[AudioToolbox] Some AudioToolbox APIs not yet implemented in Xcode13](https://github.com/xamarin/xamarin-macios/issues/12489)

**Comment by dalexsoto** [comment]
Nothing here was a breaking change but enhancements, @mandel-macaque and myself reviewed the list and decided this issue is good to go.
