### ISSUE TITLE
[.NET 6] External linker issues

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12657]
This issue lists all issues from the [mono/linker](https://github.com/mono/linker) repository that affect our .NET 6 effort.

Issues in any dotnet/* repository are listed in #8901.

The checkbox should be checked once the external issue is fixed, and the issue
moved down to "Fixed in <external repo>". When we've removed any workarounds or
implemented other related behavior to the issue in question the issue should
be moved down to "Fixed in our repo".

Equivalent issue for .NET 7: #14549.

Known breaking changes in .NET 6+ should be listed here: #8900.
Known breaking changes in CoreCLR should be listed here: #10795.

P0: something that's blocking other work for us
P1: something we can't go to stable with
P2: neither P0 nor P1

### Moved to .NET 7 (#14549)

* [x] [Setting NullabilityInfoContextSupport=false prevents ILLink.Substitutions.xml from being removed from System.Runtime.InteropServices.dll](https://github.com/dotnet/linker/issues/2661)
    * Nothing to do on our side (except bump) once this is fixed.

### Fixed in our repo

* [x] ~[Custom steps can't use error codes outside [1000, 2000]](https://github.com/mono/linker/issues/1596)~
    * https://github.com/xamarin/xamarin-macios/pull/14253
* [x] ~[The Mono.Cecil version in the Microsoft.NET.ILLink NuGet is wrong](https://github.com/mono/linker/issues/2173)~
* [x] ~[iOS: AssemblyDefinition.MainModule.FileName is not set](https://github.com/mono/linker/issues/1313)~
    * Will be fixed with #10772.
* [x] ~[error IL1001: Failed to process 'resource System.Private.CoreLib.xml in System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Feature 'sre' does not specify a 'featurevalue' attribute](https://github.com/mono/linker/issues/1351)~
* [x] ~[XmlSerializer.Serialize doesn't work when using TrimMode=link](https://github.com/dotnet/runtime/issues/41389)~
    * Revert once fixed: [`9cbf145` (#9509)](https://github.com/xamarin/xamarin-macios/pull/9509/commits/9cbf14500b3182a076bcffa3e308d1d708c1ba86)
    * Reverted: 710604a867d8c52de961fd59acbc844936adfd86
* [x] ~[AnnotationStore.SetMethodStubValue should be in the reference assembly](https://github.com/mono/linker/issues/1461)~
    * Revert: https://github.com/xamarin/xamarin-macios/pull/10450
* [x] ~[The same assembly is loaded multiple times if it passed as multiple --custom-step arguments](https://github.com/mono/linker/issues/1314)~
* [x] ~[Unable to resolve some types from System.Runtime.dll in custom linker step](https://github.com/mono/linker/issues/2267) ~
* [x] ~[Trimming BlazorWeather app is slow](https://github.com/mono/linker/issues/2089)~
* [x] ~[The 'seal' optimization fails with XmlSerializer](https://github.com/mono/linker/issues/2266)~ (not a bug in the linker)
* [x] ~[SweepStep doesn't process all type references for forwarded types](https://github.com/mono/linker/issues/1576)~
    * Blocking #9862
* [x] ~[NRE in SubStepsDispatcher](https://github.com/mono/linker/issues/1458)~
    * Reverted with https://github.com/xamarin/xamarin-macios/pull/11064
* [x] ~[Linker doesn't consider assembly references from custom attributes](https://github.com/mono/linker/issues/1304)~
    * Reverted: https://github.com/xamarin/xamarin-macios/commit/aa671914f9693176547a4fca3b5f061c6a6fce2d
* [x] ~[AnnotationStore.AddPreservedMethod (MethodDefinition key, MethodDefinition method) should be in the reference assembly](https://github.com/mono/linker/issues/1456)~
    * Workaround removed: https://github.com/xamarin/xamarin-macios/commit/fc5ae53649c527561dc90a4d57f352ef041403bf
* [x] ~[Crash after linking code using DataContractSerializer](https://github.com/dotnet/runtime/issues/41525)~
  * reverted with https://github.com/xamarin/xamarin-macios/pull/11042 https://github.com/xamarin/xamarin-macios/commit/bf8bcda9fe0285478624d10e4c3215a255af1e1c
* [x] ~[Processed debug symbols aren't copied to the publish directory](https://github.com/mono/linker/issues/1331)~
* [x] ~[Type converters are linked away in .NET 5+ when using TrimMode=link](https://github.com/dotnet/runtime/issues/41390)~
* [x] ~[LinkContext.GetAssemblies should be exposed in the reference assembly](https://github.com/mono/linker/issues/1455)~
    * By design
* [x] ~[Linker does not remove unused method when the method implements interface](https://github.com/mono/linker/issues/1459)~
    * By design
* [x] ~[IL1012: Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero](https://github.com/mono/linker/issues/1435)~
    * Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/9462
    * Revert: https://github.com/xamarin/xamarin-macios/pull/9863
