### ISSUE TITLE
[.NET 7] External dotnet issues

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#14548]
This issue lists all issues from any dotnet/* repository that affect our .NET 7 effort.

Issues in the [dotnet/linker](https://github.com/dotnet/linker) repository are listed in dotnet/runtime#14549.

The checkbox should be checked once the external issue is fixed, and the issue moved down to "Fixed in &lt;external repo&gt;". When we've removed any workarounds or implemented other related behavior to the issue in question (or verified that nothing else needs to be done) the issue should be moved down to "Fixed in our repo".

Equivalent issue for .NET 6: dotnet/runtime#8901.

Known breaking changes in .NET 6+ should be listed here: [no issue created yet, create one if needed]
Known breaking changes in CoreCLR should be listed here: [no issue created yet, create one if needed]

* P0: something that's blocking other work for us
* P1: something we can't go to stable with
* P2: neither P0 nor P1

### P2

* [x] [[API Proposal]: Add back ObsoletedInOSPlatformAttribute for .NET 7](https://github.com/dotnet/runtime/issues/68557)
* [ ] [Marshal.AllocHGlobal/FreeHGlobal is ~150x slower in .NET than legacy mono on device (tvOS)](https://github.com/dotnet/runtime/issues/58939)
* [ ] [[API Proposal]: (Re)introduce WeakAttribute that makes a field behave as if it were a WeakReference](https://github.com/dotnet/runtime/issues/68702)
* [x] [iOS: crash when profiling dotnet-podcasts](https://github.com/dotnet/runtime/issues/71492)

### Fixed in the dotnet repo

* [x] ~[GlobalizationNative_LoadICUData never called when using Invariant mode (Mac Catalyst and other Apple platforms)](https://github.com/dotnet/linker/issues/2759)~ No need for us to update anything.

**Comment by rolfbjarne** [comment]
Closing, since we're about to release .NET 7.
