### ISSUE TITLE
Support NativeAOT as a third runtime variant with Xamarin for iOS platforms

### ISSUE THREAD

**Issue by ivanpovazan** [xamarin/xamarin-macios#17339]
## Description

To enable [Supporting NativeAOT on iOS platforms as an experimental feature in .NET8](https://github.com/dotnet/runtime/issues/80905) it is required to adjust Xamarin runtime, build system and SDK accordingly.

## Tasks

The following list of tasks give a top-level overview of work that is required to enable this feature:

- [ ] Introduce new managed-to-native bridge for NativeAOT runtime
- [ ] Enable building Xamarin framework and runtime libraries for NativeAOT runtime
- [ ] Enable Xamarin SDK for iOS platforms to build applications with NativeAOT compiler, framework and runtime libraries 
- [ ] #17324
- [ ] Enable Xamarin tests with NativeAOT

/cc: @rolfbjarne 

---
PS The list of tasks is not complete. Feel free to extend it, change it and add more context.

**Comment by ivanpovazan** [comment]
> - [ ] Introduce new managed-to-native bridge for NativeAOT runtime

The bridge will be responsible for properly initialising the NativeAOT runtime, invoking any managed code initialisation e.g.: https://github.com/xamarin/xamarin-macios/blob/608765e2c9e474c494958844a94354f90fa42f36/src/ObjCRuntime/Runtime.cs#L232 , and finally invoking the managed Main method. 

See this comment for more information: https://github.com/dotnet/runtime/issues/77957#issuecomment-1402191474

**Comment by jkotas** [comment]
> Introduce new managed-to-native bridge for NativeAOT runtime

Why is this bridge better than just injecting static constructor into the app with default bootstrapper? Injecting static constructor into the app looks more composable.

**Comment by ivanpovazan** [comment]
> Why is this bridge better than just injecting static constructor into the app with default bootstrapper? Injecting static constructor into the app looks more composable.

If you are referring to the `default bootstrapper` provided by NativeAOT, it currently cannot be used from a native hosting app, when the managed executable is compiled as a static library, as the ILCompiler will not expose its managed Main method entry point (reported here: https://github.com/dotnet/runtime/issues/81097).

@rolfbjarne also gave an explanation on why it is required Xamarin to act as a native hosting application here: https://github.com/dotnet/runtime/issues/77957#issuecomment-1403752893

Finally, the requirement for:
> Introduce new managed-to-native bridge for NativeAOT runtime

is written in more general terms, as mono and coreCLR runtimes have their dedicated bridges, so supporting NativeAOT would use the same logic without changing current implementation much. 
Afaik, injecting static constructor does not allow the method to have parameters, so if we would want to use it for initializing Xamarin's ObjCRuntime, we would have to change the code to PInvoke into the native to get the required parameters. It is not my call, but this sounds like more work (especially making sure that the change does not break what is already supported).
