### ISSUE TITLE
[Xcode15] Checklist before shipping

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#18556]
The following are changes that had to be added to support Xcode15 and might need to be reverted in the final version:

- [x] https://github.com/xamarin/xamarin-macios/issues/18693 - We do, moving to .NET 9
- [x] https://github.com/xamarin/xamarin-macios/issues/18655
- [x] https://github.com/xamarin/xamarin-macios/issues/18656

**Comment by rolfbjarne** [comment]
All done.
