### ISSUE TITLE
Tracking the addition of src/Resources.resx localization

### ISSUE THREAD

**Issue by tj-devel709** [xamarin/xamarin-macios#19645]
Right now, we use OneLoc for our localization, but the `src/Resources.resx` is still hooked up to our old method of XLIFF localization. To make sure the transition is smooth, I'll map out the steps needed to hook up these translations to OneLoc.

- [ ] Add the src/Resources.resx to the `LocProject.json.in` and have the CI create the initial `src/src/TranslatedAssemblies/Resources.*.resx` files
- [ ] Wait some days / a week for the OneLoc team to consume the new translations. Their tool will commit the not-yet-usable translated .lcl files into the `Localization` branch and the [xamarin.macios-legoChanges](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=18272&_a=summary) pipeline will take those commits and make a PR (or a few PRs) into main.
- [ ] During the Sunday cron job CI (or ran manually with the 'manuallyCreateLocPR' flag selected) the [xamarin-macios-translations](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=17751&_a=summary) pipeline will consume the .lcl files and create a PR into main with the usable translations into `src/TranslatedAssemblies/Resources.*.resx` where they will be available for our customers.
- [ ] By this point, we will want to remove any references to XLIFF or .xlf in our repo.
