### ISSUE TITLE
Xcode 10.2: list of changes to be reviewed/reverted before final release

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#5086]
**Xcode 10 (pending rdar)**

- [ ] rdar://41135211: `RPSystemBroadcastPickerView` is **not** [available on sim](https://github.com/xamarin/xamarin-macios/pull/4249/files#r195288042). Still failing with Xcode 10.2.
- [x] [rdar://41110708]() [introspection] CMMovementDisorderManager isn't usable for now: #4306. Requires an entitlement that's only available from Apple by request.
- [x] [rdar://41123682](https://trello.com/c/Eyox7vlH): TVElementUpdateType* enum values changed. #5849
- [x] [rdar://43425168](https://trello.com/c/dtVv2a6R): IN*WorkoutIntentResponseCode enum values changed. #5850
- [X] [rdar://44983420](https://trello.com/c/R1EGBDkA/134-44983420-vtsessionsetproperty-kvtdecompressionpropertykeyrealtime-not-supported-on-iphone-xs-only) VTSessionSetProperty kVTDecompressionPropertyKey_RealTime not supported on iPhone X[s] only. Found by QA and filed in #4900

**Xcode 10.2**

- [x] [rdar://47596444]() Missing `PKDisbursementVoucher.h` in beta 1 (incomplete PassKit bindings)

**Comment by rolfbjarne** [comment]
This all looks good for the Xcode 10.2 release.

* RPSystemBroadcastPickerView: still not available.
* CMMovementDisorderManager: Requires an entitlement that's only available from Apple by request. IMHO we should just ignore CMMovementDisorderManager in our tests.
* TVElementUpdateType* enum values changed: Yes, Apple did breaking changes. We'll have to break our code as well (but no hurry).
* IN*WorkoutIntentResponseCode enum values changed: Yes, Apple did breaking changes. We'll have to break our code as well (but no hurry).
* kVTDecompressionPropertyKey_RealTime seems to work on my iPhone X, but this doesn't require any code changes from what I can see.

**Comment by VincentDondain** [comment]
kVTDecompressionPropertyKey_RealTime now works on iPhone Xs with 12.2 GM / 12.3. Apple replied to the radar: https://trello.com/c/R1EGBDkA

**Comment by spouliot** [comment]
rdar://41123682: TVElementUpdateType* enum values changed. #5849
fixed in https://github.com/xamarin/xamarin-macios/pull/5849

**Comment by spouliot** [comment]
rdar://41110708 [introspection] CMMovementDisorderManager isn't usable for now: #4306. Requires an entitlement that's only available from Apple by request.
fixed in https://github.com/xamarin/xamarin-macios/pull/4306

**Comment by spouliot** [comment]
xcode10.2 is out, closing

**Comment by spouliot** [comment]
(single) leftover moved to https://github.com/xamarin/xamarin-macios/issues/5906
