### ISSUE TITLE
XAMCORE_4_0 Audit List

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5107]
In some future day we may have a chance to break API compatibility. 

When that day comes we should fix up every single API mistake we can. This is a list of items we should audit.

- [x] ~Drop support for iOS 32-bit?~ We still support iOS 32-bit in .NET, and we will until our minimum OS version is 11+.
- [x] The "old" XM audit bug list from 2015 - https://bugzilla.xamarin.com/show_bug.cgi?id=31549
    - [x] Rename: #13824
        ```
        [Lion]
        [Export ("frameForItemAtIndex:withNumberOfItems:")]
        CGRect FrameForItemAtIndex (nint index, nint numberOfItems);
        ```
    - [x] ~NSAttributedString contains an existing ContainsAttachments property.  10,11 added a ContainsAttachmentsInRange method.  Can't name the method ContainsAttachments because it conflicts with the property, but ContainsAttachmentsInRange (used for now) is an ugly name.~ Nothing can be done here.
    - [x] NSTableView.DragImageForRowsWithIndexestableColumnseventoffset should be DragImageForRows. #13723.
    - [x] interface MKUserLocation : IMKAnnotation should be MKAnnotation _not possible, see #14041_
    - [x] ~Double exported "worksWhenModal" selector~ Don't know what this is talking about, can't find any problems with the "worksWhenModal" selector that looks like this.
    - [x] Invalid enum sizes: https://bugzilla.xamarin.com/show_bug.cgi?id=30719
    - [x] NSPasteboardItemDataProvider's FinishedWithDataProvider should not be required.
    - [x] ~https://github.com/xamarin/xamarin-macios/pull/929: All of the PresentError in AppKit need love.~ This can be done in a non-breaking way.
    - [x] Api inconsistency #13824
        ```
        NSMenuItemCell
        
        `cell.StateImageWidth () - cell.KeyEquivalentWidth`
        
        one is a method... one a property!
        ```
    - [x] Need an override for CreateCGImage that accepts (CIImage, CGRect, CIFormat, CGColorSpace) (Bindings have int instead of CIFormat). ~#13829~ already done some time ago
    - [x] AudioComponentDescription.ComponentSubType should be of type AudioUnitSubType instead of int. #13827
    - [x] Apple added a number of "smart" enums by renaming NSStrings with a typedef. If/when we break API compat, we should adopt those. _This has been fixed in various XAMCORE_4_0 defines already_
    - [x] NSWorkspace.SharedWorkspace.OpenURLs are inconsistent. #14028
    - [x] NSLayoutManager has numerous methods that are not well named. #13776
    - [x] On NSTextFieldDelegate this is a _terrible_ name: _Not worth it to change_
        ```
		[Export ("controlTextDidChange:"), EventArgs ("NSNotification")]
		void Changed (NSNotification notification);
        ```
- [x] Other bugs listed with [APIBreak] - https://bugzilla.xamarin.com/buglist.cgi?quicksearch=[APIBreak]
    - [x] https://bugzilla.xamarin.com/show_bug.cgi?id=40095: https://github.com/xamarin/xamarin-macios/pull/13624
    - [x] https://github.com/xamarin/xamarin-macios/issues/14047 (old: https://bugzilla.xamarin.com/show_bug.cgi?id=44957): _We don't want to do this_
    - [x] https://bugzilla.xamarin.com/show_bug.cgi?id=46316: https://github.com/xamarin/xamarin-macios/pull/13626
- [x] Issues marked with breaking-change - https://github.com/xamarin/xamarin-macios/issues?q=is%3Aopen+is%3Aissue+label%3Abreaking-change+-milestone%3AXAMCORE_5_0+
- [x] Audit `[Sealed]` items, as some were added during work arounds for binding mistakes. [Example](https://github.com/xamarin/xamarin-macios/commit/7d88592a68618176454b63ef72c66bc59acf3ee3) 
    * #14052
    * #14054
    * #14058
- [x] Consider https://github.com/xamarin/xamarin-macios/issues/5110 and other immutable changes on our data structure wrappings
- [x] ~Look at the types we use from System.Drawing and see if we can improve that scenario.~ This is done as part of .NET 6.
- [x] Change some non-optimal default values to better default values
    - [x] Make --dlsym:false the default for all assemblies, not just ours. _This can be done later, it's not an API breaking change_
    - [x] Turn on exception marshalling by default. #14051
- [x] Change constraint according to comment here: https://github.com/xamarin/xamarin-macios/blob/544925738de4a724611c8743408ab9b637fa4605/src/ObjCRuntime/Blocks.cs#L239: https://github.com/xamarin/xamarin-macios/pull/13606.
- [x] Remove `CFNetwork` namespace, including `MessageHandler`, from Xamarin.Mac. #14056
- [x] Depending on OS versions supported remove `CFNetworkHandler` (minimum iOS 8) _We can do this at a later stage_
- [x] Remove [Runtime.GetSurfacedObjects](https://github.com/xamarin/xamarin-macios/blob/b1feb2fd75a2e4b61e2e6d82fb4b3b7e74334292/src/ObjCRuntime/Runtime.iOS.cs#L56-L59): https://github.com/xamarin/xamarin-macios/pull/13608
- [x] Move System.Drawing.[Point[F]|Rectangle[F]|Size[F] types out of platform assemblies. _This is already a side effect of .NET._
- [x] [Move System.Drawing.Colors out of OpenTK-1.0.dll](https://github.com/xamarin/xamarin-macios/issues/5273): _This is already a side effect of .NET._
- [x] Move OpenTK types out of platform assemblies: https://github.com/mono/opentk/issues/19 and https://gist.github.com/rolfbjarne/f3e2030c5b334146c2af488f33973bab. _Tracked here: https://github.com/xamarin/xamarin-macios/issues/13160_
- [x] Audit availability attributes
    - [x] Remove ObjCRuntime.AvailabilityAttribute (and maybe rename ObjCRuntime.AvailabilityBaseAttribute to ObjCRuntime.AvailabilityAttribute). _This has been done as part of the .NET migration._
    - [x] Check if the `onlyOn64` logic is still applicable (it's not for tvOS for instance, where the [API will always be 64-bit](https://gist.github.com/rolfbjarne/61967cb1dab3aa65f7121a72f02661f5), and it might be true for our iOS/macOS bindings too at that point). _This has been done as part of the .NET migration._
- [x] Make ObjCRuntime.Runtime.Arch a readonly field (#5518).
- [x] [Change Full Target Framework Identifier](https://github.com/xamarin/xamarin-macios/issues/5691): N/A, this is already a side effect of .NET.
- [x] Fix incorrectly abstract members in UITextInputTraits (#5831): https://github.com/xamarin/xamarin-macios/pull/13607
- [x] Make AutoGeneratedName true by default. https://github.com/xamarin/xamarin-macios/pull/13619
- [x] All deprecated API, example: https://github.com/xamarin/xamarin-macios/pull/6476/files _tracked in #13621_
- [x] AUParameter/AUParameterNode extensions calling into [obsolete generated code](https://github.com/xamarin/xamarin-macios/pull/7562#discussion_r355490169) #13899

**Comment by Perksey** [comment]
`Move OpenTK types out of platform assemblies`
I'm glad this is being considered for XAMCORE 4.0, and I apologise on behalf of my team for our agressive behaviour in mono/opentk#19. It'll be nice to be able to use OpenTK 3.0 on Xamarin platforms again :)

**Comment by rolfbjarne** [comment]
Everything is this list is either fixed or tracked in other issues, so this can be closed.
