### ISSUE TITLE
[d16-2] Issues tracked for release

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#6033]
**Notes**
* any issue listed here should also be part of the release notes known issues (for previews)
* do not refer to this issue in commits (use the specific issue)

**Blockers**

* [x] ~~XI/XM [CS0246 / Build failure for missing System.Drawing types](https://github.com/mono/mono/issues/13483) - https://github.com/xamarin/xamarin-macios/pull/6035 (d16-2)~~
* [x] ~~XI [Application Submissions Rejection](https://github.com/mono/mono/issues/14290) - https://github.com/mono/mono/pull/14316 (master)~~
* [x] ~~XM [MM5109 / Native linking failure - `Undefined symbols for architecture x86_64`](https://github.com/xamarin/xamarin-macios/issues/5954)~~

**Major**

* [x] ~~XI watchOS S4 (arm64_32) support - https://github.com/xamarin/xamarin-macios/pull/6040 (master) https://github.com/xamarin/xamarin-macios/pull/6100 (d16-2)~~
* [ ] watchOS (older) regression - https://github.com/mono/mono/issues/13006

**Other lists** (can include duplicates of above and less critical issues)
* [Mono issues on 2019-02 affecting XI/XM](https://github.com/mono/mono/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222019-02+%286.0.xx%29%22+label%3Atarget-xamarin-ios)
* [macios issues on d16-2 milestone](https://github.com/xamarin/xamarin-macios/issues?q=is%3Aopen+is%3Aissue+milestone%3Ad16-2)

**Comment by rolfbjarne** [comment]
There are also [4 xamarin-ios](https://github.com/mono/mono/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222019-02+%286.0.xx%29%22+label%3Atarget-xamarin-ios) issues for mono's  `2019-02` milestone: 
* [[ios] Non-public API usage when submitting app](https://github.com/mono/mono/issues/14290)
* [Interpreter crashes when running monotouch-test](https://github.com/mono/mono/issues/14246)
* [Adding System.Drawing.Common.dll reference for XI/XA projects](https://github.com/mono/mono/issues/13483) - this is the same as #6011 from above.
* [[watchOS/LLVM] Test crash (don't link)](https://github.com/mono/mono/issues/13006)

**Comment by spouliot** [comment]
@rolfbjarne the first one is already in the list too (Application Submissions Rejection) but I'll edit the description with the link

**Comment by chamons** [comment]
We shipped the watchOS regression, and d16-2 is stable.
