### ISSUE TITLE
[Meta] Xcode 11 Support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6206]
This is a meta issue tracking the status of our Xcode 11 support.

## Follow our work

The current status of our bindings are [on our wiki](https://github.com/xamarin/xamarin-macios/wiki/xcode11-Bindings-Status).

You can see the latest commits in our [branch](https://github.com/xamarin/xamarin-macios/tree/xcode11) and follow our discussions in our [public development channel](https://gitter.im/xamarin/xamarin-macios).

## Status

Xcode 11 **Beta 2** is out and we are working on bindings along with test stabilization. 

There is a [known issue](https://github.com/xamarin/xamarin-macios/issues/6452) with our installer, where an override in System Preferences is needed to install.

## Contributing

- [Open PR and issues on the `xcode11` milestone](https://github.com/xamarin/xamarin-macios/milestone/22)
- [Changes to review/revert before release](https://github.com/xamarin/xamarin-macios/issues/6212)

## Known Issues

- [ ] [Simulators do not launch after upgrading to Xcode 11 beta 1. **Contains a workaround.**](https://github.com/xamarin/xamarin-macios/issues/6216)
- [ ] [Xcode 9.4 needed for 32b Mac apps crashes when accepting the license on Catalina](https://github.com/xamarin/xamarin-macios/issues/6217) 
- [ ] [XI/XM packages can't be installed without override in System Preferences (Security) (signing?)](https://github.com/xamarin/xamarin-macios/issues/6452)
- [ ] [XI/XM  Xamarin packages will show dialogs in Catalina which makes the Xamarin Installer fail.](https://github.com/xamarin/xamarin-macios/issues/6528)
- [ ] [Enabling incremental builds makes app crash upon launch](https://github.com/xamarin/xamarin-macios/issues/6422)

**Comment by chamons** [comment]
To support Xcode 11, we are bucketing items into two piles:

**[xcode11-support]** - Things required to have current functionality on macOS 10.15 / Xcode 11
**[xcode11-feature]** - New functionality on macOS 10.15 / Xcode 11 (edited) 

We will prefix each issue with one of them to tag them in a searchable way (that also works well with our internal systems).

The first set `[xcode11-support]` are obviously required for any release that can't regress existing functionality. 

Here are some stand out issues of each type (you can search github for the full listing):

# [xcode11-support] 

# [xcode11-feature]

- [Add support for Catalyst/UIKitForMac](https://github.com/xamarin/xamarin-macios/issues/6210)

**Comment by chamons** [comment]
New Status Update - Xcode 11 Beta 2 is out and we are working on bindings along with test stabilization.

**Comment by chamons** [comment]
We've shipped Xcode 11 support today, and will be extending our support over time. I'm going to leave this issue open to note where we are in various areas.

**Comment by chamons** [comment]
Xcode 11 support are in stable everywhere now.
