### ISSUE TITLE
Xcode 11: list of changes to be reviewed/reverted before final release

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6212]
### Xcode 11

* [x] Simulator provisioning: https://github.com/xamarin/xamarin-macios/pull/6204/commits/8bf57063dc7af7395774be62af3917876abef853 (#6205): #6295
* [x] Mono built from source: https://github.com/xamarin/xamarin-macios/pull/6363
    Will be fixed when merged to master.
* [x] https://github.com/xamarin/xamarin-macios/pull/6204/commits/a0a23a42d692852f9235dc440aeae0410ca5222f - fix our objc_msgSend usage. Fix in progress: #6865
* [x] libmono-native naming confusion with watchOS (fixed in #6868):
    * https://github.com/xamarin/xamarin-macios/pull/6204/commits/ce5ba1e41d526eddd9b61f68fae22a747831e9f2
    * https://github.com/xamarin/xamarin-macios/pull/6204/commits/75359b53ca6717ebccd8c3525d9d3b57f00ad5e8
* [x] Photos[UI] and WatchKit are broken (Photos[UI] are fixed in #6864; WatchKit is broken by design and won't be fixed)
    * https://github.com/xamarin/xamarin-macios/pull/6204/commits/60a5392d359ad76db334a3d9f764997f9b2fde02
    * https://github.com/xamarin/xamarin-macios/pull/6204/commits/67e497abe84b9e455201a9d89a9d14bd1d1ca36e
    * https://github.com/xamarin/xamarin-macios/pull/6332/commits/2827195b635b77d536926ed08c4f59e57e563905
    * Feedback [FB6148992](https://trello.com/c/F00N60Ys/140-fb6148992-the-ios-sdk-does-not-contain-the-watchkit-framework) (The iOS SDK does not contain the WatchKit framework)
    * Feedback [FB6149017](https://trello.com/c/7ucYvjH7/141-fb6149017-the-photos-framework-doesnt-compile-as-objective-c) (The Photos framework doesn't compile as Objective-C++)
    * https://github.com/xamarin/xamarin-macios/commit/1b02f0f61694627fb44f0301c1571896ba40c7de
    * https://github.com/xamarin/xamarin-macios/pull/6333/commits/4494ccf9791fbe81458a3c38e3649cf8bcecc5a6
* [x] Update `TBD` in `wkwebkit` (https://github.com/xamarin/xamarin-macios/pull/6354) on the replacement is added (in a future beta)
* Generator
    * [x] [Generated binding compile time error when conforming to 2 protocols with the same @required member](https://github.com/xamarin/xamarin-macios/issues/6366). _Fixed: #6961_.
* [x] min watchOS simulator is bumped to 4.0 because earlier are broken in Xcode (#6515). _Fixed in #6769_
* [x] Image captioning tests partially disabled (https://github.com/xamarin/xamarin-macios/pull/6559/commits/612a74a0fd9482ce2277843c10ca6d5f408dd328). _Fixed: #6905_
* [x] [Add MediaPlayer APIs that require AVFoundation changes](https://github.com/xamarin/xamarin-macios/issues/6597). _Fixed: #6942._
* [x] [[UIKit] Generic types in UIKit break the registrar ](https://github.com/xamarin/xamarin-macios/issues/6567)
* [x] [API has _Nullable attribute, but crashes if passing NULL, so we might want to throw ArgumentNullException if Apple doesn't fix their bug](https://github.com/xamarin/maccore/issues/1898) _Fixed: #6894_
* [x] [Some APIs are ambiguous, leading to build issues](https://github.com/xamarin/xamarin-macios/issues/6724)
* [x] [Introspection.CheckSymbols : dlsym() did not find mono_native_initialize(); clang change?]()https://github.com/xamarin/maccore/issues/1809
* [x] [[avfoundation] Needed to remove default .ctor on `AVCaptureSynchronizedDepthData` to avoid crashing introspection](https://github.com/xamarin/xamarin-macios/pull/6798)
* [x] Intents sample no longer passes Apple checks (https://github.com/xamarin/xamarin-macios/issues/6920)
### Postponed until later

* [ ] [Reenable bcl device tests for Xcode 11](https://github.com/xamarin/maccore/issues/1808)
    * Can only be done after merging the xcode11 branch back to master/d16-3.
* [ ] [Check FontManagerTest RegisterFontDescriptors_WithCallback, stopped working at beta 5](https://github.com/xamarin/xamarin-macios/issues/6690)
* [ ] Broken `object_getClass`: https://github.com/xamarin/xamarin-macios/commit/70844a81df218f9464750c6140059a9c9659ea68 ([FB6153904](https://trello.com/c/2g7qtnGO/143-fb6153904-classcopyprotocollist-crashes-in-ios-13))
    * Feedback has not been answered.
    * Still broken in Xcode 11 b7.

**Comment by venkatvidyut** [comment]
MTOUCH : error MT4109: Failed to compile the generated registrar code i'm still facing the problem.

**Comment by chamons** [comment]
@venkatvidyut Please open a new issue with steps to reproduce and full build logs.

**Comment by chamons** [comment]
As Xcode 11 is out and the other issues are tasked out, I am closing this issue and unpinning.
