### ISSUE TITLE
[.NET 6] External dotnet issues

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#8901]
This issue lists all issues from any dotnet/* repository that affect our .NET 6 effort (so far [dotnet/runtime](https://github.com/dotnet/runtime), [dotnet/sdk](https://github.com/dotnet/sdk) and [dotnet/roslyn](https://github.com/dotnet/roslyn)).

Issues in the [mono/linker](https://github.com/mono/linker) repository are listed in #12657.

The checkbox should be checked once the external issue is fixed, and the issue
moved down to "Fixed in &lt;external repo&gt;". When we've removed any workarounds or
implemented other related behavior to the issue in question (or verified that nothing else needs to be done)
the issue should be moved down to "Fixed in our repo".

Equivalent issue for .NET 7: #14548.

Known breaking changes in .NET 6+ should be listed here: #8900.
Known breaking changes in CoreCLR should be listed here: #10795.

* P0: something that's blocking other work for us
* P1: something we can't go to stable with
* P2: neither P0 nor P1

### Moved to .NET 7 (#14548).

* [x] [Marshal.AllocHGlobal/FreeHGlobal is ~150x slower in .NET than legacy mono on device (tvOS)](https://github.com/dotnet/runtime/issues/58939): moved to .NET 7

### Fixed in the dotnet repo

* [x] [Mono: the runtime packages for .NET 6+ do not contain the runtime as a .framework for iOS/tvOS/watchOS](https://github.com/dotnet/runtime/issues/42846)
    * Ref: [Ship a .framework version of Mono](https://github.com/dotnet/runtime/pull/53370)

### Fixed in our repo

* [x] ~[XmlSerializer tries to use Reflection.Emit even if RuntimeFeature.IsDynamicCodeSupported is false]~(https://github.com/dotnet/runtime/issues/59167)
    * [x] https://github.com/xamarin/xamarin-macios/pull/14255
* [x] ~[Console.Write prints a new line on iOS](https://github.com/dotnet/runtime/issues/36440)~
* [x] ~[[dotnet] Missing mono-cil-strip (or alternative)](https://github.com/xamarin/xamarin-macios/issues/11445)~
* [x] ~[DOTNETSDK_WORKLOAD_MANIFEST_ROOTS pointing to workloads that are not lowercased fails](https://github.com/dotnet/sdk/issues/19994)~ Worked around.
* [x] ~[Mono: UnmanagedCallersOnly functions with ref parameters aren't considered blittable by the AOT compiler](https://github.com/dotnet/runtime/issues/60113)~ By design
* [x] ~[[mono][aot] .aotdata files size increase compared to _legacy_ mono](https://github.com/dotnet/runtime/issues/57689)~
* [x] ~[macOS (Xamarin): failure to build X509Chain](https://github.com/dotnet/runtime/issues/57630)~
* [x] ~[iOS: LLVM fails for ios-arm](https://github.com/dotnet/runtime/issues/58112)~
    * [x] Revert when fixed: https://github.com/xamarin/SubmissionSamples/pull/38/commits/df098670d0eac78a2d32f4909ba2b586042ef6aa
* [x] ~[iOS: building with LLVM causes some exception catch clauses to not work](https://github.com/dotnet/runtime/issues/56100)~
* [x] * [x] ~[Binary addition of interpolated strings mangles the string](https://github.com/dotnet/roslyn/issues/55461)~
* [x] ~[Mono: The PINVOKE_OVERRIDE callback doesn't work when AOT-compiling code with direct-pinvoke](https://github.com/dotnet/runtime/issues/55733)~
    * Revert: #12528
* [x] ~[Add back `ObsoletedInOSPlatformAttribute` for net6](https://github.com/dotnet/runtime/issues/47601)~
    * ~blocker for https://github.com/xamarin/xamarin-macios/issues/10170~ we use `[Obsolete]` as a _close_ match
* [x] ~[iOS/AOT: XmlSerializer.Deserialize throws Attempting to JIT compile method 'void Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializerContract:.ctor ()' while running in aot-only mode. ](https://github.com/dotnet/runtime/issues/56533)~
* [x] ~[iOS: Attempting to JIT compile method '(wrapper dynamic-method) string object:lambda_method1 (System.Runtime.CompilerServices.Closure)' while running in aot-only mode.](https://github.com/dotnet/runtime/issues/47112)~
    * Revert: #12527. 
* [x] ~[iOS: Attempting to JIT compile method '(wrapper dynamic-method) void object:WriteArrayOfintToXml (System.Runtime.Serialization.XmlWriterDelegator,object,System.Runtime.Serialization.XmlObjectSerializerWriteContext,System.Runtime.Serialization.CollectionDataContract)' while running in aot-only mode.](https://github.com/dotnet/runtime/issues/47114)~
    * Revert: #12527. 
* ~[x] [iOS (and other Apple platforms): System.Private.CoreLib.dll has P/Invokes to a libhostpolicy library that isn't shipped](https://github.com/dotnet/runtime/issues/38543)~
    * Revert once fixed: 919edef176
    * Revert: #12527. 
* [x] ~[AppHost should be disabled by default for macOS like it is for iOS / tvOS / Mac Catalyst / Android](https://github.com/dotnet/runtime/issues/53307)~
* [x] ~[How to handle Runtime Pack naming when targeting > 1 VM](https://github.com/dotnet/runtime/issues/34193)~
    * Revert/update once fixed: fa50f40bea21dc69d342622ca0e83e43f56c930a
* [x] ~[Mono: AOT compiler can't compile System.Net.SafeDeleteSslContext:ReadFromConnection (Mac Catalyst)](https://github.com/dotnet/runtime/issues/55736)~
* [x] ~[iOS (and other Apple platforms): the BCL has P/Invokes to libraries and/or functions that don't exist](https://github.com/dotnet/runtime/issues/47533)~
    * Revert once fixed: cf2b3c4ec37e168d23b664e1157355d150548c44
    * It might be possible to revert code elsewhere as well.
    * Reverted: #12011.
* [x] ~[It's not possible for a workload to set a default RuntimeIdentifier](https://github.com/dotnet/runtime/issues/54406)~
* [x] ~[iOS/tvOS/MacCatalyst: some HttpClientHandler properties behave differently now](https://github.com/dotnet/runtime/issues/55986)~
* [x] ~[There doesn't seem to be a way to execute tasks or targets for 'dotnet run'](https://github.com/dotnet/sdk/issues/18436)~
    Not fixed, but we found a workaround: https://github.com/xamarin/xamarin-macios/commit/9930ddc6dd0acc261982a24eec20de4f764e88a0
* [x] ~[Symbols required for AOT are private in libmonosgen-2.0.dylib](https://github.com/dotnet/runtime/issues/55000)~
* [x] ~[[tvOS] System.Net.Security depends on non-existant System.Net.Security.Native](https://github.com/dotnet/runtime/issues/45535)~
    * Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/10182/commits/39948aa2c90e1d0edc9f21dc3528878740b4385e
* [x] ~[iOS: error: Ran out of trampolines of type 1 in '/private/var/containers/Bundle/Application/D4741AA0-B7E1-442E-AAA2-BFD48F71C744/dont link.app/System.Private.CoreLib.dll' (limit 0).](https://github.com/dotnet/runtime/issues/47047)~
* [x] ~[ThreadPool and Xamarin platform integration](https://github.com/dotnet/runtime/issues/32543)~
    * Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/9465
    * #12248.
* [x] [[.NET] Only the invariant culture works](https://github.com/xamarin/xamarin-macios/issues/8906)
    * ~Revert once fixed: 6fd9e151ecfae6c8073b9ddbca6985de0e6e5ddf, https://github.com/xamarin/xamarin-macios/pull/9498~
    * ~blocked on https://github.com/dotnet/runtime/issues/50290~
    * ~tvOS support is still missing -> https://github.com/dotnet/runtime/issues/50912~ [fix](https://github.com/xamarin/xamarin-macios/pull/11247)
    * ~Calendar tests are still failing (iOS) w/ICU -> https://github.com/dotnet/runtime/issues/50859~
    * ~Catalyst does not ship with ICU support -> https://github.com/xamarin/xamarin-macios/issues/11392~
* [x] ~[iOS: Attempting to JIT compile method '(wrapper native-to-managed) void System.Net.NetworkInformation.BsdNetworkInterface/<>c__DisplayClass5_0:<GetBsdNetworkInterfaces>b__0 (intptr,Interop/Sys/IpAddressInfo*)' while running in aot-only mode.](https://github.com/dotnet/runtime/issues/47120)~
    * https://github.com/xamarin/xamarin-macios/pull/12253
* [x] ~[MonoVM: Missing runtime workloads for Mac Catalyst and macOS](https://github.com/dotnet/runtime/issues/53579)~
* [x] ~[RuntimeConfigParserTasksAssemblyPath in Microsoft.NET.Runtime.RuntimeConfigParser.Task is wrong](https://github.com/dotnet/runtime/issues/53811)~
* [x] ~[Mono: the runtime packages for .NET 6+ for iOS/tvOS/watchOS do not contain the static libraries required for interpreter support](https://github.com/dotnet/runtime/issues/43943)~
* [x] ~[Microsoft.NET.Workload.Mono.Toolchain does not get me the arm64 AOT compiler for Mac Catalyst](https://github.com/dotnet/runtime/issues/54996)~
* [x] ~[Launching dotnet using mono on macOS will hang if dotnet launches processes]~(https://github.com/dotnet/runtime/issues/55645)~
* [x] ~['dotnet run -- args' requires 'args' to exist](https://github.com/dotnet/runtime/issues/54548)~
* [x] ~[Mac Catalyst: TimeZoneInfo.FindSystemTimeZoneById fails](https://github.com/dotnet/runtime/issues/55941)~ Dup of #11392
* [x] ~[MonoVM's arm64 binaries for macOS don't have Apple Silicon support](https://github.com/dotnet/runtime/issues/52635)~
* [x] ~[iOS/MonoVM: waiting doesn't wait](https://github.com/dotnet/runtime/issues/50245)~
* [x] ~[iOS: NullReferenceException in HttpConnectionPool when using HttpWebRequest](https://github.com/dotnet/runtime/issues/49201)~
    * Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/10788/commits/904e81fcf80f2ee74e91acd979c065266668777d -> reverted
* [x] ~[Add Mono.osx-arm64 runtime pack and produce new runtime pack](https://github.com/dotnet/runtime/issues/48531)~
* [x] ~[tvOS: Mono runtime for device is missing bitcode](https://github.com/dotnet/runtime/issues/48508)~ (P4 bump fixed that)
* [x] ~[Mac Catalyst: Need dllmap support](https://github.com/dotnet/runtime/issues/48110)~
    * Use PINVOKE_CALLBACK instead: 9153edebda911f4b2d66d7facdd2fccc418eb7f2
* [x] ~[Mac Catalyst: GC doesn't collect object with finalizers](https://github.com/dotnet/runtime/issues/47407)~
* [x] ~[iOS: System.Runtime.Loader.AssemblyLoadContext.MonoResolveUnmanagedDllUsingEvent is linked away when still needed](https://github.com/dotnet/runtime/issues/46908)~
    * Revert once fixed:
        * https://github.com/rolfbjarne/xamarin-macios/commit/ece7188a2e68f0aec16062f6847190869da7e6ca -> reverted
        * https://github.com/xamarin/xamarin-macios/commit/29727d6a8da87f4e9f0db5bb7f8e24929078332d -> reverted
* [x] ~[AOT compiler for .NET/iOS not built with MONOTOUCH defined](https://github.com/dotnet/runtime/issues/45002)~
* [x] ~[[mono] iOS FullAOT crashes with condition `method->is_inflated' not met](https://github.com/dotnet/runtime/issues/35674)~
* [x] ~[System.Security tests fail on iOS](https://github.com/dotnet/runtime/issues/36897)~
    * Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/9463, [`6a2f1db` (#9509)](https://github.com/xamarin/xamarin-macios/pull/9509/commits/6a2f1dbc291a730de4bb3ab6e6d41cff938e3874), [`e8c3891` (#9509)](https://github.com/xamarin/xamarin-macios/pull/9509/commits/e8c389164deea9f171ec796e6704a9bbe6c84140), https://github.com/xamarin/xamarin-macios/search?q=36897&unscoped_q=36897
    * Reverted: 2ecbb07068899fd3d7c1858e870ca1ddf33d5d3f
* [x] ~[Dynamic libraries in the microsoft.netcore.app.runtime.ios-x64 package has incorrect identity](https://github.com/dotnet/runtime/issues/34637)~
    * Revert once fixed: be3568f893: 7ac5b95bd7cef87ba4f45d043c85c39dad53ebf0
* [x] ~[Type.IsInterface returns different values between .NET and Mono for reference types](https://github.com/dotnet/runtime/issues/39068)~
    * ~Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/9466~ By design
* [x] ~[iOS: System.Net.NetworkInformation.Ping.Send throws System.Net.NetworkInformation.PingException: An exception occurred during a Ping request](https://github.com/dotnet/runtime/issues/41355)~
    * Revert once fixed: [`77f9a4d` (#9509)](https://github.com/xamarin/xamarin-macios/pull/9509/commits/77f9a4d733ca64bc434c042c919f55b4c8e21a05)
    * Reverted: 974aad0a26854b900e072ad3076a76b7674450f8
* [x] ~[iOS: Some of the Environment.SpecialFolders values are incorrect with regards to Xamarin.iOS](https://github.com/dotnet/runtime/issues/41383)~
    * Revert once fixed: [`eb79bcc` (#9509)](https://github.com/xamarin/xamarin-macios/pull/9509/commits/eb79bccd749b9f1982e32d8874d847338365231c)
    * Revert PR: https://github.com/rolfbjarne/xamarin-macios/commit/88c1a34b85c8b19eabb1d1b59f5765db7b65d51d
* [x] ~[Linq.Queryable.FirstOrDefault doesn't work when using TrimMode=link](https://github.com/dotnet/runtime/issues/41392)~
    * Revert once fixed: [`ae0649f` (#9509)](https://github.com/xamarin/xamarin-macios/pull/9509/commits/ae0649f4e59c0ea435429799eeeb5f4759a4195d)
    * Reverted with https://github.com/xamarin/xamarin-macios/pull/11041 https://github.com/xamarin/xamarin-macios/commit/f6630725141df49578ed446fc2cbe48bac4ef5e2
* [x] ~[MonoVM: add back dllmap support for macOS](https://github.com/dotnet/runtime/issues/43204)~
    * Revert once fixed: https://github.com/xamarin/xamarin-macios/pull/10123
    * Reverted:  9153edebda911f4b2d66d7facdd2fccc418eb7f2
* [x] ~[Mono: ConstructorInfo.ToString () returns unexpected format](https://github.com/dotnet/runtime/issues/36688)~
    * Revert once fixed: f69ed9a25e
    * Reverted: https://github.com/xamarin/xamarin-macios/pull/9738
* [x] ~[Allow using `SupportedOSPlatformAttribute` on interfaces](https://github.com/dotnet/runtime/issues/47599)~
* [x] ~[ICU / TimeZone hang in P4](https://unicode-org.atlassian.net/browse/ICU-21591)~
  * revert https://github.com/xamarin/xamarin-macios/pull/11175/commits/5fdd4e2dec744e8741beb2edf9c3d20873107283 -> reverted
* [x] ~[.NET 5: can't build F# projects](https://github.com/dotnet/sdk/issues/12954)~
     * Revert once fixed: https://github.com/xamarin/xamarin-macios/blob/6a1e8acbb053f5bf1a908f5e4e836f36fff30a6a/tests/fsharplibrary/dotnet/shared.targets#L12-L13
     * Reverted: https://github.com/xamarin/xamarin-macios/pull/9845
