### ISSUE TITLE
Xcode 12.2 final audit checklist

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#9744]
Following the spirit of https://github.com/xamarin/xamarin-macios/issues/8943

## Stuff we need to review / fix before the final / stable release of the SDK

- [ ] [Enable watchOS tests again](https://github.com/xamarin/xamarin-macios/blob/6e8eed3e76c7a222ca5009ac8133985013963fa1/tests/xharness/Jenkins/Jenkins.cs#L38)
- [ ] Check on `MediaAccessibility/ImageCaptioningTest.cs` `SetCaption` tests, added a parrot for Beta 2
- [x] ~Figure out a way to include IKVM (mono/ikvm-fork#20 and mono/ikvm-fork#21) changes into xcode12.2 without bumping mono~ -> https://github.com/xamarin/xamarin-macios/pull/9783
- [ ] Double check ModelIO and remove ignore added here https://github.com/xamarin/xamarin-macios/pull/9844
- [ ] Check on `CoreSpotlight.CSLocalizedString` not a hard blocker since it is also broken in GM

**Comment by spouliot** [comment]
Unchecked items moved to https://github.com/xamarin/xamarin-macios/issues/10165 (Xcode 12.3 checklist) since fixing any of them means a commit into that branch
